/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.ConexionB;
import Modelo.UsuarioDAO;
import Modelo.UsuarioM;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Usuarios extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    int fila;
    
    public Usuarios() {
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        txtidU = new javax.swing.JTextField();
        txtnombreU = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnRegresarU = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        cbxperfil = new javax.swing.JComboBox<>();
        cbxestado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Clave:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Perfil:");

        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });

        txtidU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidUActionPerformed(evt);
            }
        });

        txtnombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreUActionPerformed(evt);
            }
        });
        txtnombreU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreUKeyTyped(evt);
            }
        });

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnRegresarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/regresar.png"))); // NOI18N
        btnRegresarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarUActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("REGISTRO DE USUARIOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "CLAVE", "PERFIL", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneliminar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Estado:");

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        cbxperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar perfil", "Administrador", "Vendedor" }));

        cbxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar estado", "Activo", "No activo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel7)
                .addGap(641, 641, 641)
                .addComponent(btnRegresarU)
                .addGap(33, 198, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtidU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtclave, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxestado, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)
                                .addComponent(cbxperfil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnguardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnguardar)
                                    .addComponent(btnactualizar)
                                    .addComponent(btnlimpiar))
                                .addGap(50, 50, 50))
                            .addComponent(btnRegresarU, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void limpiar() {
        txtidU.setText("");
        txtnombreU.setText("");
        txtusuario.setText("");
        txtclave.setText("");
        cbxperfil.setSelectedIndex(0);
        cbxestado.setSelectedIndex(0);
    }

    private void btnRegresarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarUActionPerformed
        Principal p=new Principal();
        p.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnRegresarUActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        int Fila = tabla.getSelectedRow();

        PreparedStatement ps = null;
        try {
            ConexionB objCon = new ConexionB();
            Connection conn = objCon.getConnection();
            ps = conn.prepareStatement("UPDATE cuenta SET nombre=?, user=?, pass=?, rol=?, estado=? WHERE idCuenta=?");

            ps.setString(1, txtnombreU.getText());
            ps.setString(2, txtusuario.getText());
            ps.setString(3, txtclave.getText());
            ps.setString(4, cbxperfil.getSelectedItem().toString());
            ps.setString(5, cbxestado.getSelectedItem().toString());
            ps.setString(6, txtidU.getText());
            ps.execute();

            JOptionPane.showMessageDialog(null, "UsuarioModificado");
            tabla.setValueAt(txtidU.getText(), Fila, 0);
            tabla.setValueAt(txtnombreU.getText(), Fila, 1);
            tabla.setValueAt(txtusuario.getText(), Fila, 2);
            tabla.setValueAt(txtclave.getText(), Fila, 3);

            limpiar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Modificar Producto");
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        UsuarioDAO modsql=new UsuarioDAO();
        UsuarioM mod=new UsuarioM();
   
        if (txtidU.getText().equals("") ||  txtnombreU.getText().equals("") ||  txtusuario.getText().equals("") ||  txtclave.getText().equals("")  ) {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos, debe llenar todos los campos ");
        } else {
           
            if (modsql.existeUsuario(txtusuario.getText()) ==0) {
                mod.setIdU(Integer.parseInt(txtidU.getText()));
                 mod.setNombre(txtnombreU.getText());
                 mod.setUsuario(txtusuario.getText());
                  mod.setClave(txtclave.getText());
                  mod.setPerfil(cbxperfil.getSelectedItem().toString());
                  mod.setPerfil(cbxestado.getSelectedItem().toString());
             if (modsql.registrar(mod)) {
                  JOptionPane.showMessageDialog(null, "Registro guardado");
                  String []info=new String[6];
                  info[0]=txtidU.getText();
                  info[1]=txtnombreU.getText();
                  info[2]=txtusuario.getText();
                  info[3]=txtclave.getText();
                 info[4]=cbxperfil.getSelectedItem().toString();
                 info[5]=cbxestado.getSelectedItem().toString();
                  modelo.addRow(info);
                
              } else {
               JOptionPane.showMessageDialog(null, "Error al guardar");
                }
                   } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe");
              }        
        }     
    }//GEN-LAST:event_btnguardarActionPerformed

    
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      
        int rpta= JOptionPane.showConfirmDialog(null, "Estás seguro de eliminar el registro?");
        if (rpta==JOptionPane.YES_OPTION) {
            PreparedStatement ps=null;
           try{
                ConexionB conn=new ConexionB();
                Connection con =conn.getConnection();
                int filaa=tabla.getSelectedRow();
                String cod= tabla.getValueAt(filaa, 0).toString();     
                ps=con.prepareStatement("DELETE FROM cuenta WHERE idCuenta=?");
                ps.setString(1, cod);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Registro eliminado");
                modelo.removeRow(filaa);
                } catch(SQLException ex){
                     System.out.println(ex.toString());
                }
        }   
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtnombreUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreUKeyTyped
        char c=evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c> ' ')) evt.consume(); 
    
    }//GEN-LAST:event_txtnombreUKeyTyped

    private void txtidUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidUActionPerformed

    private void txtnombreUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreUActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txtidU.setText("");
        txtnombreU.setText("");
        txtusuario.setText("");
        txtclave.setText("");
        cbxperfil.setSelectedItem(0);
        cbxestado.setSelectedItem(0);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int seleccion=tabla.getSelectedRow();
         txtidU.setText(tabla.getValueAt(seleccion, 0).toString());
         txtnombreU.setText(tabla.getValueAt(seleccion, 1).toString());
         txtusuario.setText(tabla.getValueAt(seleccion, 2).toString());
         txtclave.setText(tabla.getValueAt(seleccion, 3).toString());
         cbxperfil.setSelectedItem(tabla.getValueAt(seleccion, 4).toString());
         cbxestado.setSelectedItem(tabla.getValueAt(seleccion, 5).toString());
  
    }//GEN-LAST:event_tablaMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String campo= txtbuscar.getText();
        String where="";
        
        if (!"".equals(campo)) {
            where="WHERE user= '"+ campo+"'";
        }    
         try{
            modelo=new DefaultTableModel();
            tabla.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            ConexionB conn=new ConexionB();
            Connection con =conn.getConnection();
            
            String sql="SELECT idCuenta, nombre, user, pass, rol, estado FROM cuenta "+where;
             System.out.println(sql);
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();      
            ResultSetMetaData rsMd= rs.getMetaData();
            int cantColum= rsMd.getColumnCount();
            modelo.addColumn("ID");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("USUARIO");
            modelo.addColumn("CLAVE");
            modelo.addColumn("PERFIL");
            modelo.addColumn("ESTADO");     
            while(rs.next()){
                Object[] filas=new Object[cantColum];
                for (int i = 0; i < cantColum; i++) {
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        } catch(SQLException ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarU;
    public javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox<String> cbxestado;
    private javax.swing.JComboBox<String> cbxperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    private javax.swing.JTextField txtbuscar;
    public javax.swing.JPasswordField txtclave;
    public javax.swing.JTextField txtidU;
    public javax.swing.JTextField txtnombreU;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
